theme: jekyll-theme-cayman

title: "CBL2M"
description: "End-to-End Lyric-to-Melody Generation via Chord Integration and Bar-Level Modeling"

# Optional: Additional configuration
markdown: kramdown
